// app/components/BackToTop.tsx
// Floating "back to top" button. Hidden until the page scrolls past 400px.
import { useEffect, useState } from 'react';
import { ArrowUp } from 'lucide-react';

export function BackToTop() {
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const onScroll = () => setVisible(window.scrollY > 400);
    onScroll();
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  const scrollUp = () => window.scrollTo({ top: 0, behavior: 'smooth' });

  return (
    <button
      type="button"
      onClick={scrollUp}
      aria-label="回到顶部"
      className={[
        'fixed bottom-8 right-8 z-50 inline-flex h-10 w-10 items-center justify-center rounded-full',
        'bg-primary text-primary-foreground shadow-lg shadow-primary/20',
        'transition-all duration-300 hover:-translate-y-0.5 hover:shadow-xl',
        'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/50',
        visible ? 'opacity-100 translate-y-0' : 'pointer-events-none opacity-0 translate-y-4',
      ].join(' ')}
    >
      <ArrowUp className="h-4 w-4" />
    </button>
  );
}

// app/components/BackToTop.vue
<template>
  <Transition name="back-to-top">
    <button
      v-if="isVisible"
      @click="scrollToTop"
      class="fixed bottom-6 right-6 z-50 p-3 rounded-full bg-white dark:bg-neutral-800 shadow-lg hover:shadow-xl transition-all duration-300 hover:scale-110 border border-neutral-200 dark:border-neutral-700"
      aria-label="返回顶部"
    >
      <svg
        class="w-6 h-6 text-neutral-700 dark:text-neutral-300"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
        stroke-width="2"
      >
        <path
          d="M5 15l7-7 7 7M5 19h14"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </svg>
    </button>
  </Transition>
</template>

<script setup lang="ts">
const isVisible = ref(false)
const isClient = import.meta.client
const scrollThreshold = 300

const scrollToTop = () => {
  if (isClient) {
    window.scrollTo({
      top: 0,
      behavior: 'smooth'
    })
  } else {
    return
  }
}

const updateVisibility = () => {
  if (isClient) {
    isVisible.value = window.pageYOffset > scrollThreshold
  } else {
    return
  }
}

onMounted(() => {
  if (isClient) {
    window.addEventListener('scroll', updateVisibility)
    updateVisibility()
  } else {
    return
  }
})

onUnmounted(() => {
  if (isClient) {
    window.removeEventListener('scroll', updateVisibility)
  } else {
    return
  }
})
</script>

<style scoped>
.back-to-top-enter-active,
.back-to-top-leave-active {
  transition: all 0.3s ease;
}

.back-to-top-enter-from,
.back-to-top-leave-to {
  opacity: 0;
  transform: translateY(20px);
}

.back-to-top-enter-to,
.back-to-top-leave-from {
  opacity: 1;
  transform: translateY(0);
}
</style>
