// app/components/PostsHeatmap.tsx
// Posts heatmap: a 14-week × 7-day grid (周日..周六 row labels). Each cell is
// shaded by how many posts were published that day; days outside the window
// are transparent. The header row carries the section title on the left and
// the yearly summary on the right.
import { useMemo } from 'react';
import { BarChart3 } from 'lucide-react';
import { Tooltip, TooltipContent, TooltipTrigger } from '~/components/ui/tooltip';

interface PostStub {
  date: string;
}

interface PostsHeatmapProps {
  posts: PostStub[];
  totalCount: number;
}

const WEEKS_TO_SHOW = 14;
const SUMMARY_DAYS = 365;
const WEEKDAY_LABELS = ['周日', '周一', '周二', '周三', '周四', '周五', '周六'];

function toDateKey(date: Date): string {
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
}

// 0 = no posts, 4 = five or more.
function levelOf(count: number): number {
  if (count >= 5) return 4;
  if (count >= 3) return 3;
  if (count >= 2) return 2;
  if (count >= 1) return 1;
  return 0;
}

function buildTitle(count: number, date: Date): string {
  const label = date.toLocaleDateString('zh-CN', { year: 'numeric', month: 'long', day: 'numeric' });
  return count === 0 ? `无文章 · ${label}` : `${count} 篇文章 · ${label}`;
}

export function PostsHeatmap({ posts, totalCount }: PostsHeatmapProps) {
  const { weeks, yearActiveDays } = useMemo(() => {
    const counts = new Map<string, number>();
    for (const p of posts) {
      if (!p.date) continue;
      const d = new Date(p.date);
      if (Number.isNaN(d.getTime())) continue;
      const key = toDateKey(d);
      counts.set(key, (counts.get(key) ?? 0) + 1);
    }

    const today = new Date();
    today.setHours(0, 0, 0, 0);
    // 年度统计与网格窗口分开算：摘要按近一年，网格按最近 14 周。
    let yearActiveDays = 0;
    for (let offset = 0; offset < SUMMARY_DAYS; offset += 1) {
      const date = new Date(today);
      date.setDate(today.getDate() - offset);
      if ((counts.get(toDateKey(date)) ?? 0) > 0) yearActiveDays += 1;
    }

    const rangeStart = new Date(today);
    rangeStart.setDate(rangeStart.getDate() - (WEEKS_TO_SHOW * 7 - 1));
    // Align the grid to full weeks: back to Sunday, forward to Saturday.
    const gridStart = new Date(rangeStart);
    gridStart.setDate(gridStart.getDate() - gridStart.getDay());

    const weekCount = Math.ceil(((today.getTime() - gridStart.getTime()) / 86_400_000 + 1) / 7);
    const weeks: Array<Array<{ count: number; title: string } | null>> = [];

    for (let w = 0; w < weekCount; w += 1) {
      const week: Array<{ count: number; title: string } | null> = [];
      for (let d = 0; d < 7; d += 1) {
        const date = new Date(gridStart);
        date.setDate(gridStart.getDate() + w * 7 + d);
        if (date < rangeStart || date > today) {
          week.push(null);
          continue;
        }
        const count = counts.get(toDateKey(date)) ?? 0;
        week.push({ count, title: buildTitle(count, date) });
      }
      weeks.push(week);
    }

    return { weeks, yearActiveDays };
  }, [posts]);

  return (
    <div>
      {/* 头部：标题居左，年度统计居右两行 */}
      <div className="flex items-start justify-between gap-2 mb-4">
        <h3 className="inline-flex items-center gap-2 text-[1.05rem] font-semibold text-foreground">
          <BarChart3 className="h-4 w-4 text-(--brand)" aria-hidden />
          统计
        </h3>
        <div className="mono-meta text-right leading-relaxed">
          <span className="block">共 {totalCount} 篇文章</span>
          <span className="block">过去一年 {yearActiveDays} 天有更新</span>
        </div>
      </div>

      <div className="grid grid-cols-[38px_1fr] pt-1">
        <div className="grid grid-rows-[repeat(7,14px)] gap-[2px] pr-1.5">
          {WEEKDAY_LABELS.map((label) => (
            <span key={label} className="mono-meta !text-[0.6rem] h-[14px] leading-[14px]">
              {label}
            </span>
          ))}
        </div>
        <div className="flex gap-[2px]">
          {weeks.map((week, wi) => (
            <div key={wi} className="grid grid-rows-[repeat(7,14px)] gap-[2px] flex-1">
              {week.map((day, di) =>
                day ? (
                  <Tooltip key={`${wi}-${di}`}>
                    <TooltipTrigger asChild>
                      <span
                        className={`block h-[14px] w-auto ${day.count > 0 ? 'heatmap-cell-active' : 'heatmap-cell-empty'}`}
                        style={day.count > 0 ? { opacity: 0.45 + levelOf(day.count) * 0.14 } : undefined}
                      />
                    </TooltipTrigger>
                    <TooltipContent>{day.title}</TooltipContent>
                  </Tooltip>
                ) : (
                  <span key={`${wi}-${di}`} />
                )
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// app/components/PostsHeatmap.vue
<template>
  <aside class="posts-heatmap">
    <div class="heatmap-header">
      <div class="heatmap-title">
        <svg class="heatmap-icon" aria-hidden="true">
          <use xlink:href="#icon-tongji"></use>
        </svg>
        <span>统计</span>
      </div>
      <div v-if="summaryText" class="heatmap-subtitle">{{ summaryText }}</div>
      <div v-else class="heatmap-subtitle"></div>
    </div>
    <div v-if="hasError" class="heatmap-empty">加载失败</div>
    <div v-else-if="isLoading" class="heatmap-loading">加载中...</div>
    <div v-else-if="weeks.length > 0" class="heatmap-body">
      <div class="heatmap-grid">
        <div class="weekday-labels">
          <span class="weekday-label">周日</span>
          <span class="weekday-label">周一</span>
          <span class="weekday-label">周二</span>
          <span class="weekday-label">周三</span>
          <span class="weekday-label">周四</span>
          <span class="weekday-label">周五</span>
          <span class="weekday-label">周六</span>
        </div>
        <div class="weeks-grid">
          <div v-for="(week, weekIndex) in weeks" :key="weekIndex" class="week-column">
            <span
              v-for="(day, dayIndex) in week"
              :key="dayIndex"
              class="day-cell"
              :class="day.className"
              :title="day.title"
            ></span>
          </div>
        </div>
      </div>
    </div>
    <div v-else class="heatmap-empty">暂无数据</div>
  </aside>
</template>

<script setup>
const props = defineProps({
  posts: {
    type: Array,
    default: () => []
  },
  isLoading: {
    type: Boolean,
    default: false
  },
  hasError: {
    type: Boolean,
    default: false
  }
})

const weeksToShow = 16
const daysToShow = weeksToShow * 7
const summaryDays = 365
const englishMonthMap = {
  January: 0,
  February: 1,
  March: 2,
  April: 3,
  May: 4,
  June: 5,
  July: 6,
  August: 7,
  September: 8,
  October: 9,
  November: 10,
  December: 11
}

const normalizeDate = (date) => {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate())
}

const parsePostDate = (value) => {
  if (typeof value === 'string') {
    const trimmed = value.trim()
    const isoMatch = trimmed.match(/^(\d{4})-(\d{2})-(\d{2})/)

    if (isoMatch) {
      const year = Number.parseInt(isoMatch[1], 10)
      const month = Number.parseInt(isoMatch[2], 10) - 1
      const day = Number.parseInt(isoMatch[3], 10)
      return new Date(year, month, day)
    } else {
      const englishMatch = trimmed.match(/^([A-Za-z]+)\s+(\d{1,2}),\s*(\d{4})$/)

      if (englishMatch) {
        const monthIndex = englishMonthMap[englishMatch[1]]

        if (typeof monthIndex === 'number') {
          const year = Number.parseInt(englishMatch[3], 10)
          const day = Number.parseInt(englishMatch[2], 10)
          return new Date(year, monthIndex, day)
        } else {
          return null
        }
      } else {
        const parsed = new Date(trimmed)

        if (Number.isNaN(parsed.getTime())) {
          return null
        } else {
          return parsed
        }
      }
    }
  } else {
    return null
  }
}

const padNumber = (value) => {
  if (value < 10) {
    return `0${value}`
  } else {
    return String(value)
  }
}

const buildDateKey = (date) => {
  const year = date.getFullYear()
  const month = padNumber(date.getMonth() + 1)
  const day = padNumber(date.getDate())
  return `${year}-${month}-${day}`
}

const getWeekdayIndex = (date) => {
  return date.getDay()
}

const diffDays = (start, end) => {
  const ms = end.getTime() - start.getTime()
  return Math.floor(ms / (1000 * 60 * 60 * 24))
}

const resolveLevel = (count) => {
  if (count >= 5) {
    return 4
  } else if (count >= 3) {
    return 3
  } else if (count >= 2) {
    return 2
  } else if (count >= 1) {
    return 1
  } else {
    return 0
  }
}

const buildTitle = (count, date) => {
  const label = date.toLocaleDateString('zh-CN', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })

  if (count === 0) {
    return `无文章 · ${label}`
  } else if (count === 1) {
    return `1 篇文章 · ${label}`
  } else {
    return `${count} 篇文章 · ${label}`
  }
}

const buildCountsMap = (posts) => {
  const counts = new Map()

  posts.forEach((post) => {
    let dateValue = null

    if (post && typeof post === 'object') {
      dateValue = post.date
    } else {
      dateValue = null
    }

    const date = parsePostDate(dateValue)

    if (date) {
      const key = buildDateKey(date)
      const current = counts.get(key)

      if (typeof current === 'number') {
        counts.set(key, current + 1)
      } else {
        counts.set(key, 1)
      }
    } else {
      return
    }
  })

  return counts
}

const buildHeatmap = (counts) => {
  const today = normalizeDate(new Date())
  const rangeStart = new Date(today)
  rangeStart.setDate(rangeStart.getDate() - daysToShow + 1)

  const gridStart = new Date(rangeStart)
  gridStart.setDate(gridStart.getDate() - getWeekdayIndex(gridStart))

  const gridEnd = new Date(today)
  gridEnd.setDate(gridEnd.getDate() + (6 - getWeekdayIndex(gridEnd)))

  const totalDays = diffDays(gridStart, gridEnd) + 1
  const weekCount = Math.ceil(totalDays / 7)
  const weeks = []
  let activeDays = 0
  let totalPosts = 0

  for (let weekIndex = 0; weekIndex < weekCount; weekIndex += 1) {
    const week = []

    for (let dayIndex = 0; dayIndex < 7; dayIndex += 1) {
      const offset = weekIndex * 7 + dayIndex
      const date = new Date(gridStart)
      date.setDate(gridStart.getDate() + offset)

      const inRange = date >= rangeStart && date <= today
      let count = 0
      let className = 'level-empty'
      let title = ''

      if (inRange) {
        const key = buildDateKey(date)
        const stored = counts.get(key)

        if (typeof stored === 'number') {
          count = stored
        } else {
          count = 0
        }

        totalPosts += count

        if (count > 0) {
          activeDays += 1
        } else {
          activeDays = activeDays
        }

        className = `level-${resolveLevel(count)}`
        title = buildTitle(count, date)
      } else {
        count = 0
        className = 'level-empty'
        title = ''
      }

      week.push({
        date,
        count,
        inRange,
        className,
        title
      })
    }

    weeks.push(week)
  }

  return {
    weeks,
    activeDays,
    totalPosts
  }
}

const countsMap = computed(() => {
  let rawPosts = []

  if (Array.isArray(props.posts)) {
    rawPosts = props.posts
  } else {
    rawPosts = []
  }
  return buildCountsMap(rawPosts)
})

const buildSummary = (counts) => {
  const today = normalizeDate(new Date())
  const rangeStart = new Date(today)
  rangeStart.setDate(rangeStart.getDate() - summaryDays + 1)
  let activeDays = 0
  let totalPosts = 0

  for (let offset = 0; offset < summaryDays; offset += 1) {
    const date = new Date(rangeStart)
    date.setDate(rangeStart.getDate() + offset)
    const key = buildDateKey(date)
    const stored = counts.get(key)
    let count = 0

    if (typeof stored === 'number') {
      count = stored
    } else {
      count = 0
    }

    totalPosts += count

    if (count > 0) {
      activeDays += 1
    } else {
      activeDays = activeDays
    }
  }

  return {
    activeDays,
    totalPosts
  }
}

const heatmapData = computed(() => {
  return buildHeatmap(countsMap.value)
})

const summaryData = computed(() => {
  return buildSummary(countsMap.value)
})

const weeks = computed(() => {
  return heatmapData.value.weeks
})

const summaryText = computed(() => {
  const activeDays = summaryData.value.activeDays
  const totalPosts = summaryData.value.totalPosts

  if (activeDays > 0) {
    return `过去一年 ${activeDays} 天有更新`
  } else if (totalPosts > 0) {
    return `过去一年 ${totalPosts} 篇文章`
  } else {
    return ''
  }
})
</script>

<style scoped>
.posts-heatmap {
  --cell-size: 9px;
  --cell-gap: 3px;
  padding: 0;
  border: none;
  background: transparent;
  margin-bottom: 1.5rem;
}

.heatmap-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 0.75rem;
  gap: 0.5rem;
}

.heatmap-title {
  display: inline-flex;
  align-items: center;
  gap: 0.4rem;
  font-size: 0.95rem;
  font-weight: 600;
  color: rgb(var(--color-neutral-800));
}

.heatmap-icon {
  width: 14px;
  height: 14px;
  color: rgb(var(--color-primary-500));
}

.heatmap-subtitle {
  font-size: 0.7rem;
  color: var(--text-color-2);
}

.heatmap-grid {
  display: grid;
  grid-template-columns: 34px 1fr;
}

.weekday-labels {
  display: grid;
  grid-template-rows: repeat(7, var(--cell-size));
  gap: var(--cell-gap);
  font-size: 0.65rem;
  color: var(--text-color-2);
  padding-right: 6px;
}

.weekday-label {
  height: var(--cell-size);
  line-height: var(--cell-size);
  font-size: 0.6rem;
}

.weeks-grid {
  display: flex;
  gap: var(--cell-gap);
}

.week-column {
  display: grid;
  grid-template-rows: repeat(7, var(--cell-size));
  gap: var(--cell-gap);
}

.day-cell {
  width: var(--cell-size);
  height: var(--cell-size);
  border-radius: 0;
  background: rgba(var(--color-neutral-200), 0.6);
}

.day-cell.level-0 {
  background: rgba(var(--color-neutral-200), 0.7);
}

.day-cell.level-1 {
  background: rgba(var(--color-primary-300), 0.5);
}

.day-cell.level-2 {
  background: rgba(var(--color-primary-400), 0.6);
}

.day-cell.level-3 {
  background: rgba(var(--color-primary-500), 0.7);
}

.day-cell.level-4 {
  background: rgba(var(--color-primary-600), 0.8);
}

.day-cell.level-empty {
  background: transparent;
}

.heatmap-loading,
.heatmap-empty {
  text-align: center;
  font-size: 0.8rem;
  color: var(--text-color-2);
  padding: 1.5rem 0;
}

:global(.dark) .heatmap-title {
  color: rgb(var(--color-neutral-200));
}

:global(.dark) .heatmap-icon {
  color: rgb(var(--color-primary-400));
}

:global(.dark) .day-cell.level-0 {
  background: rgba(var(--color-neutral-700), 0.8);
}

:global(.dark) .day-cell.level-1 {
  background: rgba(var(--color-primary-700), 0.5);
}

:global(.dark) .day-cell.level-2 {
  background: rgba(var(--color-primary-600), 0.65);
}

:global(.dark) .day-cell.level-3 {
  background: rgba(var(--color-primary-500), 0.8);
}

:global(.dark) .day-cell.level-4 {
  background: rgba(var(--color-primary-400), 0.9);
}
</style>
