// app/components/friends/RSSAggregator.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, RefreshCw, Rss } from 'lucide-react';
import { Spinner } from '~/components/ui/spinner';
import { Button } from '~/components/ui/button';
import { Avatar, AvatarFallback, AvatarImage } from '~/components/ui/avatar';
import { Card } from '~/components/ui/card';
import { Empty, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from '~/components/ui/empty';
import { Skeleton } from '~/components/ui/skeleton';
import { useRelativeTime } from '~/hooks/useRelativeTime';
import type { Friend } from '~/lib/content/friends';

const PAGE_SIZE = 10;

interface FeedItem {
  title: string;
  link: string;
  pubDate: string;
  description: string;
}

interface SiteResult {
  siteName: string;
  siteUrl: string;
  siteLogo: string;
  hasRSS: boolean;
  isEmpty?: boolean;
  error?: boolean;
  errorMessage?: string;
  articles?: FeedItem[];
}

interface TimelineArticle extends FeedItem {
  siteName: string;
  siteLogo: string;
  siteUrl: string;
}

async function fetchSite(friend: Friend): Promise<SiteResult> {
  const base: SiteResult = {
    siteName: friend.name,
    siteUrl: friend.url,
    siteLogo: friend.logo,
    hasRSS: Boolean(friend.rss),
    articles: [],
  };
  if (!friend.rss) return base;
  try {
    const res = await fetch(`/api/friends?url=${encodeURIComponent(friend.url)}`);
    if (!res.ok) throw new Error(`Status code ${res.status}`);
    const data = (await res.json()) as { results: SiteResult[] };
    return data.results[0] ?? base;
  } catch (err) {
    return {
      ...base,
      error: true,
      errorMessage: err instanceof Error ? err.message : '未知错误',
    };
  }
}

function formatErrorMessage(raw: string | undefined): string {
  const message = (raw ?? '').trim() || '未知错误';
  const status = message.match(/(?:Status code|HTTP)\s+(\d+)/);
  if (status) {
    const codeMessages: Record<string, string> = {
      '404': 'RSS 地址不存在',
      '403': '访问被拒绝',
      '500': '服务器内部错误',
      '502': '网关错误',
      '503': '服务不可用',
      '504': '网关超时',
    };
    return codeMessages[status[1]] ?? `HTTP 错误 (${status[1]})`;
  }
  if (message.includes('ENOTFOUND')) return '域名无法解析';
  if (message.includes('ECONNREFUSED')) return '连接被拒绝';
  if (message.includes('timeout') || message.includes('ETIMEDOUT')) return '请求超时';
  if (message.includes('certificate') || message.includes('CERT')) return 'SSL 证书错误';
  if (message.includes('ENETUNREACH')) return '网络不可达';
  return message;
}

function SiteAvatar({ src, name }: { src: string; name: string }) {
  return (
    <Avatar className="size-10 shrink-0 border border-border">
      <AvatarImage src={src} alt={name} loading="lazy" referrerPolicy="no-referrer" />
      <AvatarFallback className="rounded-full bg-muted font-mono text-base text-(--brand)">
        {name.charAt(0).toUpperCase()}
      </AvatarFallback>
    </Avatar>
  );
}

function RelativeTime({ date }: { date: string }) {
  const label = useRelativeTime(date);
  return <time dateTime={date}>{label}</time>;
}

function MomentCard({ article }: { article: TimelineArticle }) {
  return (
    <li>
      <Card className="card-lift h-full p-6 shadow-none">
      <div className="mb-3 flex items-center gap-3">
        <SiteAvatar src={article.siteLogo} name={article.siteName} />
        <div className="min-w-0 flex-1">
          <a
            href={article.siteUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="block truncate text-sm font-semibold text-foreground transition-colors duration-200 ease hover:text-(--brand)"
          >
            {article.siteName}
          </a>
          <div className="mono-meta">
            <RelativeTime date={article.pubDate} />
          </div>
        </div>
        <Rss className="h-3.5 w-3.5 shrink-0 text-(--brand-line)" aria-hidden />
      </div>

      <h3 className="mb-1.5 text-base font-bold leading-snug">
        <a
          href={article.link}
          target="_blank"
          rel="noopener noreferrer"
          className="text-foreground transition-colors duration-200 ease hover:text-(--brand)"
        >
          {article.title}
        </a>
      </h3>
      {article.description ? (
        <p className="line-clamp-3 text-sm leading-relaxed text-muted-foreground">
          {article.description}
        </p>
      ) : null}
      </Card>
    </li>
  );
}

function FailedFeedsPanel({ failedFeeds }: { failedFeeds: SiteResult[] }) {
  return (
    <section
      className="mt-20 paper-card p-6 shadow-none"
      aria-label="RSS 获取失败列表"
    >
      <h2 className="mb-4 flex items-center gap-2 font-bold text-foreground">
        <AlertTriangle className="h-5 w-5" aria-hidden />
        RSS 获取失败 ({failedFeeds.length})
      </h2>
      <ul className="space-y-3">
        {failedFeeds.map((feed) => (
          <li
            key={feed.siteUrl}
            className="flex items-start justify-between gap-4 paper-card p-6 shadow-none"
          >
            <div className="min-w-0">
              <span className="block truncate text-sm font-semibold text-foreground">
                {feed.siteName}
              </span>
              <a
                href={feed.siteUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="mono-meta transition-colors duration-200 ease hover:text-(--brand)"
              >
                {feed.siteUrl}
              </a>
            </div>
            <span className="shrink-0 text-sm text-black/60">
              {formatErrorMessage(feed.errorMessage)}
            </span>
          </li>
        ))}
      </ul>
    </section>
  );
}

export function RSSAggregator({ friends }: { friends: Friend[] }) {
  const [results, setResults] = useState<SiteResult[] | null>(null);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [loadingMore, setLoadingMore] = useState(false);
  const [visibleCount, setVisibleCount] = useState(PAGE_SIZE);
  // load() can be triggered by the refresh button outside any effect, so the
  // unmount flag lives in a ref instead of an effect-local variable.
  const mountedRef = useRef(true);

  useEffect(() => {
    mountedRef.current = true;
    return () => {
      mountedRef.current = false;
    };
  }, []);

  // 用 ref 固化首屏入参：friends 若来自父组件的内联数组，引用变化会让 effect
  // 反复重新拉取所有站点的 RSS。
  const friendsRef = useRef(friends);
  friendsRef.current = friends;

  const load = useCallback(async () => {
    setIsRefreshing(true);
    const settled = await Promise.all(friendsRef.current.map(fetchSite));
    if (mountedRef.current) {
      setResults(settled);
      setIsRefreshing(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const { articles, failedFeeds, activeSites } = useMemo(() => {
    const list: TimelineArticle[] = [];
    const failed: SiteResult[] = [];
    let ok = 0;
    for (const r of results ?? []) {
      if (r.error) {
        failed.push(r);
        continue;
      }
      if (r.articles && r.articles.length > 0) ok += 1;
      for (const a of r.articles ?? []) {
        list.push({ ...a, siteName: r.siteName || r.siteUrl, siteLogo: r.siteLogo, siteUrl: r.siteUrl });
      }
    }
    list.sort((a, b) => new Date(b.pubDate).getTime() - new Date(a.pubDate).getTime());
    return { articles: list, failedFeeds: failed, activeSites: ok };
  }, [results]);

  const displayed = articles.slice(0, visibleCount);
  const hasMore = displayed.length < articles.length;
  const initialLoading = results === null;

  // 「加载更多」的延迟定时器要能被刷新和卸载取消：否则 300ms 内点刷新会被
  // 这个定时器再追加一页，卸载后也会继续改状态。
  const loadMoreTimerRef = useRef<number | null>(null);
  const cancelLoadMore = useCallback(() => {
    if (loadMoreTimerRef.current !== null) {
      window.clearTimeout(loadMoreTimerRef.current);
      loadMoreTimerRef.current = null;
    }
    setLoadingMore(false);
  }, []);

  useEffect(() => cancelLoadMore, [cancelLoadMore]);

  const refresh = () => {
    cancelLoadMore();
    setVisibleCount(PAGE_SIZE);
    load();
  };

  const loadMore = () => {
    if (loadingMore || !hasMore) return;
    setLoadingMore(true);
    loadMoreTimerRef.current = window.setTimeout(() => {
      loadMoreTimerRef.current = null;
      setVisibleCount((count) => count + PAGE_SIZE);
      setLoadingMore(false);
    }, 300);
  };

  return (
    <div>
      <div className="mb-6 flex items-center justify-between gap-4">
        <p className="mono-meta">
          {initialLoading
            ? '正在拉取订阅…'
            : `共 ${articles.length} 篇 · 来自 ${activeSites} 个站点${
                failedFeeds.length > 0 ? ` · ${failedFeeds.length} 个失败` : ''
              }`}
        </p>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={refresh}
          disabled={isRefreshing || initialLoading}
          className="gap-2"
        >
          <RefreshCw className={`h-4 w-4${isRefreshing ? ' animate-spin' : ''}`} aria-hidden />
          {isRefreshing ? '刷新中…' : '刷新'}
        </Button>
      </div>

      {initialLoading ? (
        <div className="space-y-5 py-4" aria-label="加载中" role="status">
          {[0, 1, 2].map((i) => (
            <div key={i} className="paper-card p-6 shadow-none">
              <div className="mb-3 flex items-center gap-3">
                <Skeleton className="size-10 rounded-full" />
                <div className="flex-1 space-y-1.5">
                  <Skeleton className="h-3.5 w-28" />
                  <Skeleton className="h-3 w-16" />
                </div>
              </div>
              <Skeleton className="mb-2 h-4 w-3/4" />
              <Skeleton className="h-3 w-full" />
              <Skeleton className="mt-1.5 h-3 w-5/6" />
            </div>
          ))}
        </div>
      ) : articles.length === 0 ? (
        <Empty className="py-12">
          <EmptyHeader>
            <EmptyMedia variant="icon">
              <Rss />
            </EmptyMedia>
            <EmptyTitle>暂无动态</EmptyTitle>
            <EmptyDescription>朋友们最近还没有发布新文章。</EmptyDescription>
          </EmptyHeader>
        </Empty>
      ) : (
        <>
          <ul className="space-y-5">
            {displayed.map((a) => (
              <MomentCard key={a.link} article={a} />
            ))}
          </ul>

          {hasMore ? (
            <div className="mt-8 text-center">
              <Button
                type="button"
                variant="outline"
                onClick={loadMore}
                disabled={loadingMore}
                className="gap-2"
              >
                {loadingMore ? <Spinner data-icon="inline-start" /> : null}
                {loadingMore ? '加载中…' : '查看更多'}
              </Button>
            </div>
          ) : null}
        </>
      )}

      {!initialLoading && failedFeeds.length > 0 ? <FailedFeedsPanel failedFeeds={failedFeeds} /> : null}
    </div>
  );
}

// app/components/friends/RSSAggregator.vue
<template>
  <div class="rss-aggregator">
    <div class="rss-header">
      <h3 class="rss-title">友链动态</h3>
      <p class="rss-desc">看看朋友们最近在写什么</p>
      <button class="refresh-btn" @click="refreshRSS" :disabled="loading">
        <svg
          v-if="!loading"
          class="icon"
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
        >
          <path d="M23 4v6h-6M1 20v-6h6" />
          <path
            d="m3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"
          />
        </svg>
        <div v-else class="spinner-small"></div>
        <span>{{ loading ? "刷新中..." : "刷新" }}</span>
      </button>
    </div>

    <div class="rss-content">
      <div v-if="loading && !articles.length" class="loading-state">
        <div class="loading-spinner">
          <div class="spinner"></div>
        </div>
        <p class="loading-text">正在获取友链动态...</p>
      </div>

      <div v-else-if="error" class="error-state">
        <div class="error-icon">
          <svg
            width="32"
            height="32"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <circle cx="12" cy="12" r="10"></circle>
            <line x1="15" y1="9" x2="9" y2="15"></line>
            <line x1="9" y1="9" x2="15" y2="15"></line>
          </svg>
        </div>
        <p class="error-text">获取动态失败</p>
        <button class="retry-btn" @click="refreshRSS">重试</button>
      </div>

      <div v-else-if="!articles.length" class="empty-state">
        <div class="empty-icon">
          <svg
            width="32"
            height="32"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <path
              d="M12 2L2 7v10c0 5.55 3.84 10.74 9 12 5.16-1.26 9-6.45 9-12V7l-10-5z"
            />
          </svg>
        </div>
        <p class="empty-text">暂无友链动态</p>
      </div>

      <div v-else class="articles-list">
        <div
          v-for="article in displayedArticles"
          :key="article.link"
          class="article-item"
        >
          <div class="article-source">
            <img
              :src="article.siteLogo"
              :alt="article.siteName"
              class="source-avatar"
              loading="lazy"
              @error="handleImageError"
            />
            <div class="source-info">
              <span class="source-name">{{ article.siteName }}</span>
              <span class="article-date">{{
                formatDate(article.pubDate)
              }}</span>
            </div>
          </div>
          <div class="article-content">
            <h4 class="article-title">
              <a :href="article.link" target="_blank" rel="noopener noreferrer">
                {{ article.title }}
              </a>
            </h4>
            <p v-if="article.description" class="article-desc">
              {{ article.description }}
            </p>
          </div>
        </div>

        <div v-if="hasMore" class="load-more">
          <button
            class="load-more-btn"
            @click="loadMore"
            :disabled="loadingMore"
          >
            <span v-if="!loadingMore">加载更多</span>
            <span v-else>加载中...</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
const props = defineProps({
  sites: {
    type: Array,
    required: true,
  },
});

const articles = ref([]);
const loading = ref(false);
const loadingMore = ref(false);
const error = ref(false);
const currentPage = ref(0);
const articlesPerPage = 10;

const displayedArticles = computed(() => {
  const start = 0;
  const end = start + (currentPage.value + 1) * articlesPerPage;
  return articles.value.slice(start, end);
});

const hasMore = computed(() => {
  return displayedArticles.value.length < articles.value.length;
});

const refreshRSS = async () => {
  loading.value = true;
  error.value = false;
  currentPage.value = 0;

  try {
    const allArticles = [];

    // 并行获取所有站点的RSS
    const promises = props.sites.map(async (site) => {
      try {
        const data = await $fetch(
          `/api/friends?url=${encodeURIComponent(site.siteUrl)}`
        );
        const siteResult = data?.results?.[0];
        if (siteResult?.articles && siteResult.articles.length > 0) {
          return siteResult.articles.map((article) => ({
            ...article,
            siteName: site.siteName,
            siteLogo: site.siteLogo,
            siteUrl: site.siteUrl,
          }));
        }
      } catch (err) {
        console.warn(`Failed to fetch RSS for ${site.siteName}:`, err);
        return [];
      }

      return [];
    });

    const results = await Promise.all(promises);
    results.forEach((siteArticles) => {
      allArticles.push(...siteArticles);
    });

    // 按发布时间排序
    articles.value = allArticles.sort(
      (a, b) => new Date(b.pubDate) - new Date(a.pubDate)
    );
  } catch (err) {
    console.error("Failed to refresh RSS:", err);
    error.value = true;
  } finally {
    loading.value = false;
  }
};

const loadMore = () => {
  if (!loadingMore.value && hasMore.value) {
    loadingMore.value = true;
    setTimeout(() => {
      currentPage.value++;
      loadingMore.value = false;
    }, 300);
  }
};

const formatDate = (dateString) => {
  try {
    const date = new Date(dateString);
    const now = new Date();
    const diffTime = Math.abs(now - date);
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

    if (diffDays === 1) {
      return "今天";
    } else if (diffDays === 2) {
      return "昨天";
    } else if (diffDays <= 7) {
      return `${diffDays - 1}天前`;
    } else {
      return date.toLocaleDateString("zh-CN", {
        month: "short",
        day: "numeric",
      });
    }
  } catch {
    return "未知日期";
  }
};

const handleImageError = (event) => {
  event.target.src =
    "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHZpZXdCb3g9IjAgMCAzMiAzMiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjMyIiBoZWlnaHQ9IjMyIiByeD0iOCIgZmlsbD0iI0YzRjRGNiIvPgo8c3ZnIHdpZHRoPSIxNiIgaGVpZ2h0PSIxNiIgdmlld0JveD0iMCAwIDE2IDE2IiBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHg9IjgiIHk9IjgiPgo8Y2lyY2xlIGN4PSI4IiBjeT0iNiIgcj0iMiIgZmlsbD0iIzlDQTNBRiIvPgo8cGF0aCBkPSJNNCAxMkM0IDkgNiA3IDggN0MxMCA3IDEyIDkgMTIgMTJINEgiIGZpbGw9IiM5Q0EzQUYiLz4KPC9zdmc+Cjwvc3ZnPgo=";
};

// 组件挂载时自动刷新
onMounted(() => {
  refreshRSS();
});
</script>

<style lang="scss" scoped>
.rss-aggregator {
  @apply rounded-2xl p-6 md:p-8;
  background: linear-gradient(
    135deg,
    rgba(var(--color-primary-50), 0.5) 0%,
    rgba(var(--color-secondary-50), 0.3) 100%
  );
  border: 1px solid rgba(var(--color-primary-200), 0.5);
  backdrop-filter: blur(10px);
}

.rss-header {
  @apply flex flex-col md:flex-row md:items-center justify-between mb-8 pb-6;
  border-bottom: 2px solid rgba(var(--color-primary-200), 0.3);
}

.rss-title {
  @apply text-2xl font-bold text-neutral-900 m-0 mb-1;
  letter-spacing: -0.02em;
}

.rss-desc {
  @apply text-sm text-neutral-600 m-0 mb-4 md:mb-0;
}

.refresh-btn {
  @apply flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-xl transition-all duration-300;
  background: linear-gradient(
    135deg,
    rgb(var(--color-primary-500)),
    rgb(var(--color-primary-600))
  );
  color: white;
  border: none;

  &:hover:not(:disabled) {
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(var(--color-primary-500), 0.3);
  }

  &:active:not(:disabled) {
    transform: translateY(0);
  }

  &:disabled {
    @apply opacity-60 cursor-not-allowed;
  }
}

.icon {
  @apply flex-shrink-0;
}

.spinner-small {
  @apply w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin;
}

.rss-content {
  @apply min-h-[200px];
}

.loading-state,
.error-state,
.empty-state {
  @apply flex flex-col items-center justify-center py-16 text-center;
}

.loading-spinner {
  @apply mb-4;
}

.spinner {
  @apply w-10 h-10 border-4 rounded-full animate-spin;
  border-color: rgba(var(--color-primary-200), 1);
  border-top-color: rgb(var(--color-primary-500));
}

.loading-text {
  @apply text-neutral-600 m-0 text-sm;
}

.error-icon,
.empty-icon {
  @apply mb-4 text-neutral-400;
}

.error-text,
.empty-text {
  @apply text-neutral-600 m-0 mb-4;
}

.retry-btn {
  @apply px-5 py-2.5 rounded-xl font-medium transition-all duration-300;
  background: linear-gradient(
    135deg,
    rgb(var(--color-primary-500)),
    rgb(var(--color-primary-600))
  );
  color: white;
  border: none;

  &:hover {
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(var(--color-primary-500), 0.3);
  }
}

.articles-list {
  @apply space-y-3;
}

.article-item {
  @apply p-5 rounded-xl transition-all duration-300;
  background: white;
  border: 1px solid rgba(var(--color-neutral-200), 0.6);

  &:hover {
    transform: translateY(-2px);
    box-shadow: 0 8px 20px rgba(var(--color-primary-500), 0.1);
    border-color: rgba(var(--color-primary-300), 0.5);
  }
}

.article-source {
  @apply flex items-center gap-3 mb-3;
}

.source-avatar {
  @apply w-10 h-10 rounded-xl object-cover flex-shrink-0;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
}

.source-info {
  @apply flex-1 min-w-0 flex items-center gap-2;
}

.source-name {
  @apply text-sm font-semibold text-neutral-900;
}

.article-date {
  @apply text-xs px-2 py-0.5 rounded-full;
  background: rgba(var(--color-primary-100), 0.6);
  color: rgb(var(--color-primary-700));
}

.article-content {
  @apply space-y-2;
}

.article-title {
  @apply m-0;
}

.article-title a {
  @apply text-base font-semibold text-neutral-900 no-underline transition-colors duration-200;

  &:hover {
    color: rgb(var(--color-primary-600));
  }
}

.article-desc {
  @apply text-sm text-neutral-600 leading-relaxed m-0;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.load-more {
  @apply text-center mt-6 pt-6;
  border-top: 2px solid rgba(var(--color-primary-200), 0.3);
}

.load-more-btn {
  @apply px-6 py-2.5 text-sm font-medium rounded-xl transition-all duration-300;
  background: linear-gradient(
    135deg,
    rgba(var(--color-primary-500), 0.1),
    rgba(var(--color-secondary-500), 0.1)
  );
  color: rgb(var(--color-primary-700));
  border: 1px solid rgba(var(--color-primary-300), 0.5);

  &:hover:not(:disabled) {
    background: linear-gradient(
      135deg,
      rgb(var(--color-primary-500)),
      rgb(var(--color-primary-600))
    );
    color: white;
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(var(--color-primary-500), 0.3);
  }

  &:disabled {
    @apply opacity-50 cursor-not-allowed;
  }
}

// 深色模式
:global(.dark) {
  .rss-aggregator {
    background: linear-gradient(
      135deg,
      rgba(var(--color-primary-900), 0.3) 0%,
      rgba(var(--color-secondary-900), 0.2) 100%
    );
    border-color: rgba(var(--color-primary-700), 0.3);
  }

  .rss-header {
    border-bottom-color: rgba(var(--color-primary-700), 0.2);
  }

  .rss-title {
    @apply text-neutral-100;
  }

  .rss-desc {
    @apply text-neutral-400;
  }

  .refresh-btn {
    background: linear-gradient(
      135deg,
      rgb(var(--color-primary-600)),
      rgb(var(--color-primary-700))
    );

    &:hover:not(:disabled) {
      box-shadow: 0 4px 12px rgba(var(--color-primary-600), 0.4);
    }
  }

  .spinner {
    border-color: rgba(var(--color-primary-400), 0.3);
    border-top-color: rgb(var(--color-primary-400));
  }

  .loading-text {
    @apply text-neutral-400;
  }

  .error-text,
  .empty-text {
    @apply text-neutral-400;
  }

  .retry-btn {
    background: linear-gradient(
      135deg,
      rgb(var(--color-primary-600)),
      rgb(var(--color-primary-700))
    );
  }

  .article-item {
    background: rgba(var(--color-neutral-900), 0.5);
    border-color: rgba(var(--color-neutral-700), 0.5);

    &:hover {
      background: rgba(var(--color-neutral-900), 0.7);
      border-color: rgba(var(--color-primary-500), 0.4);
      box-shadow: 0 8px 20px rgba(var(--color-primary-600), 0.15);
    }
  }

  .source-name {
    @apply text-neutral-100;
  }

  .article-date {
    background: rgba(var(--color-primary-900), 0.5);
    color: rgb(var(--color-primary-300));
  }

  .article-title a {
    @apply text-neutral-100;

    &:hover {
      color: rgb(var(--color-primary-400));
    }
  }

  .article-desc {
    @apply text-neutral-400;
  }

  .load-more {
    border-top-color: rgba(var(--color-primary-700), 0.2);
  }

  .load-more-btn {
    background: linear-gradient(
      135deg,
      rgba(var(--color-primary-600), 0.15),
      rgba(var(--color-secondary-600), 0.15)
    );
    color: rgb(var(--color-primary-300));
    border-color: rgba(var(--color-primary-500), 0.4);

    &:hover:not(:disabled) {
      background: linear-gradient(
        135deg,
        rgb(var(--color-primary-600)),
        rgb(var(--color-primary-700))
      );
      color: white;
    }
  }
}
</style>
